tech/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from tech import settings
from django.contrib.staticfiles import urls
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('technology.urls')),
]
urlpatterns += urls.staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

technology/urls.py
from django.conf.urls import url, include
from . import views
app_name = 'technology'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^(?P<blog_id>[0-9]+)/$', views.blog, name="blog"),
    url(r'^p/(?P<part_id>[0-9]+)/$', views.part, name="part"),
    url(r'^u/(?P<user_id>[0-9]+)/$', views.profile, name="profile")
]

technology/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Part(models.Model):
	"""docstring for part"""
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name
	class Meta:
		verbose_name = 'القسم'
		verbose_name_plural = 'الأقسام'

class Blog(models.Model):
	"""docstring for Blog"""
	title = models.CharField(max_length=200,verbose_name='العنوان')
	date = models.DateTimeField('تاريخ النشر')
	publisher = models.ForeignKey(User)
	body = models.TextField()
	image = models.ImageField()
	views = models.IntegerField(default=0)
	part = models.ForeignKey(Part)
	def __str__(self):
		return self.title
	class Meta:
		verbose_name = 'التدوينة'
		verbose_name_plural = 'التدوينات'


class Profile(models.Model):
	"""docstring for Profile"""
	user = models.OneToOneField(User)
	name = models.CharField(max_length=50)
	birth = models.DateField()
	photo = models.ImageField()
	nabda = models.CharField(max_length=300)
	class Meta:
		verbose_name = 'الصفحة الشخصية'
		verbose_name_plural = 'الصفحات الشخصية'

technology/forms.py
from django import forms
from django.contrib.auth.models import User
import re
from django.core.exceptions import ObjectDoesNotExist

class Addimg(forms.Form):
	img = forms.ImageField()

technology/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from technology.models import Blog, Part, Profile
from django.contrib.auth.models import User
# Create your views here.

best_blogs = Blog.objects.order_by("views").reverse()[:8]
parts = Part.objects.all()

def index(request):
	latest_blogs = Blog.objects.order_by("date").reverse()[:10]
	parts = Part.objects.all()
	context = {'latest_blogs':latest_blogs,
	           'best_blogs':best_blogs,
	           'parts':parts,
	           }
	return render(request,'technology/index.html',context)

def blog(request,blog_id):
	blog = get_object_or_404(Blog,pk=blog_id)
	if request:
		blog.views += 1
		blog.save()
	context = {'best_blogs':best_blogs,
	           'blog':blog,
	           'parts':parts,}
	return render(request,'technology/blog.html',context)

def profile(request,user_id):
	profile = get_object_or_404(Profile,pk=user_id)
	user = profile.user
	latest_blogs = Blog.objects.filter(publisher=user).order_by("date").reverse()
	context = {'latest_blogs':latest_blogs,'best_blogs':best_blogs,
	 'profile':profile,'user':user,'parts':parts,
}
	return render(request,'technology/profile.html',context)

def part(request,part_id):
	part = get_object_or_404(Part,pk=part_id)
	latest_blogs = Blog.objects.filter(part=part).order_by("date").reverse()[:5]
	context = {'latest_blogs':latest_blogs,'best_blogs':best_blogs,'parts':parts,
}
	return render(request,'technology/part.html',context)

technology/templates/technology/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>التقنية</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="icon" type="image/png"
     href="{% static 'files/cpu.png' %}" />
</head>

<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.9&appId=1015886131876010";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    <header class="main-header">
    <div class="head2">
    	<a href="https://www.facebook.com/" class="sm"><img src="{% static 'files/facebook.svg' %}"></a>
       	<a href="http://www.twitter.com" class="sm"><img src="{% static 'files/twitter.svg' %}"></a>
    	<a href="http://www.youtube.com" class="sm"><img src="{% static 'files/youtube.svg' %}"></a>
    	<a href="http://www.google-plus.com" class="sm"><img src="{% static 'files/google-plus.svg' %}"></a>
    </div>
    <div class="head1"><a href="{% url 'technology:index' %}"><img src="{% static 'files/logo6.png' %}"/></a></div></header>

    <nav><ul>



    	<li class="one two"><a href="{% url 'technology:index' %}" class="a">الرئيسية</a></li>
        {% for part in parts %}
        <li class="two"><a href="{% url 'technology:part' part.id %}" class="a" >{{part.name}}</a></li>
        {% endfor %}

    	<li class="two"><a class="a" id="list">المزيد ..</a>
    	<div id="ddown">
    	<a href="{% url 'technology:part' 4 %}">من نحن</a>
    	<a href="{% url 'technology:part' 5 %}">إتصل بنا</a>
    	</div></li>
    </ul></nav>

    <div class="number1">
    {% block ind %}
    {% endblock %}
    </div>

    <div class="container">
    {% block content %}
    {% endblock %}
    <aside class="main-aside">
    <p>الأكثر مشاهدة</p>
    {% for b in best_blogs %}
    <section>           
    <div class="artimg"><a href="{% url 'technology:blog' b.id %}"><img src="{{MEDIA_URL}}{{ b.image.url }}" alt="jjj" ></a></div>
    <div class="artbody">
    <a href="{% url 'technology:blog' b.id %}"><p>{{b.title}}</p></a>
    </div>
    </section>
    {% endfor %}
    </aside>
    </div>


    <footer class="main-footer"><p>جميع الحقوق محفوظة 2017</p></footer>



    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

technology/templates/technology/blog.html
{% extends 'technology/base.html' %}
{% load staticfiles %}
<head>
<link rel="stylesheet" type="text/css" href="stylesheet.css">
</head>

{% block content %}
    <div class="main-p">
    	<article class="blog">
    	    <div class="blogimg"><img src="{{MEDIA_URL}}{{ blog.image.url }}" alt="jjj" ></div>
    		<div class="blogbody">
    		<h3>{{blog.title}}</h3>
    		<span>من طرف <a href="{%url 'technology:profile' blog.publisher.id%}">{{blog.publisher.get_full_name}}</a> في {{blog.date}}
    		</span>
    		<p>{{ blog.body }}</p>
    		</div>
            <div class="fb-comments" data-href="{{request.build_absolute_url}}" data-width="100%" data-numposts="5"></div>
    	</article>
    </div>
{% endblock %}

technology/templates/technology/index.html
{% extends 'technology/base.html' %}
{% load staticfiles %}

{% block ind %}
{% for b in latest_blogs %}

    {% if forloop.counter == 1 %}
    <a href="{% url 'technology:blog' b.id %}"><div style="background-image:url('{{MEDIA_URL}}{{ b.image.url }}') " class="one"><p>{{b.title}}</p></div></a>
    {% endif %}
    {% if forloop.counter == 2 %}
    <a href="{% url 'technology:blog' b.id %}"><div style="background-image:url('{{MEDIA_URL}}{{ b.image.url }}') " class="two"><p>{{b.title}}</p></div></a>    
    {% endif %}
    {% if forloop.counter == 3 %}
    <a href="{% url 'technology:blog' b.id %}"><div style="background-image:url('{{MEDIA_URL}}{{ b.image.url }}') " class="two"><p>{{b.title}}</p></div></a>
    {% endif %}
{% endfor %}
{% endblock %}

{% block content %}
    <div class="main-p">
{% for blog in latest_blogs %}
    	<article>
    	    <div class="artimg"><a href="{% url 'technology:blog' blog.id %}"><img src="{{MEDIA_URL}}{{ blog.image.url }}" alt="jjj" ></a></div>
    		<div class="artbody">
    		<a href="{% url 'technology:blog' blog.id %}"><h3>{{blog.title}}</h3></a>
    		<span>من طرف <a href="{%url 'technology:profile' blog.publisher.id%}">{{blog.publisher.get_full_name}}</a> في {{blog.date}}
    		</span>
    		<p>{{ blog.body|slice:":255" }}</p>
    		</div>
    	</article>
{% endfor %}
    </div>
{% endblock %}

technology/templates/technology/part.html
{% extends 'technology/base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="main-p">
{% for blog in latest_blogs %}
    	<article>
    	    <div class="artimg"><a href="{% url 'technology:blog' blog.id %}"><img src="{{MEDIA_URL}}{{ blog.image.url }}" alt="jjj" ></a></div>
    		<div class="artbody">
    		<a href="{% url 'technology:blog' blog.id %}"><h3>{{blog.title}}</h3></a>
    		<span>من طرف <a href="{%url 'technology:profile' blog.publisher.id%}">{{blog.publisher.get_full_name}}</a> في {{blog.date}}
    		</span>
    		<p>{{ blog.body|slice:":255" }}</p>
    		</div>
    	</article>
{% endfor %}
    </div>
{% endblock %}

technology/templates/technology/profile.html
{% extends 'technology/base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="main-p">
    <div class="profile">
    <img src="{{MEDIA_URL}}{{ profile.photo.url }}">
    <p>{{user.get_full_name}}</p>
    </div>
    <p>تدويناتي</p>
{% for blog in latest_blogs %}
    	<article>
    	    <div class="artimg"><a href="{% url 'technology:blog' blog.id %}"><img src="{{MEDIA_URL}}{{ blog.image.url }}" alt="jjj" ></a></div>
    		<div class="artbody">
    		<a href="{% url 'technology:blog' blog.id %}"><h3>{{blog.title}}</h3></a>
    		<span>من طرف <a href="{%url 'technology:profile' blog.publisher.id%}">{{blog.publisher.get_full_name}}</a> في {{blog.date}}
    		</span>
    		<p>{{ blog.body|slice:":255" }}</p>
    		</div>
    	</article>
{% endfor %}
    </div>
{% endblock %}